trigger:
  branches:
    include:
      - main

resources:
  repositories:
  - repository: AndersonSimas/SmogIt
    type: github
    name: SmogIt
    endpoint: 'GitConnection - AndersonSimas'

variables:
  BuildDBSolution: "SmogItDB/SmogItDB/SmogItDB.sqlproj"
  BuildPlatform : 'Any cpu'
  BuildConfiguration : 'release'
  artifactName: 'SmogItDB'

name: SmogItDB.$(date:yyyyMMdd)$(rev:.r)

stages:
  - stage: Build
    displayName: "Build Database"
    jobs:
      - job: BuildDatabase
        displayName: "Build Database Solution"
        pool:
          vmImage: 'windows-latest'
        steps:
          - task: VSBuild@1
            displayName: "Build Database Solution"
            inputs: 
              platform: ${{variables.BuildPlatform}}
              configuration: ${{variables.BuildConfiguration}}
              solution: ${{variables.BuildDBSolution}}
              clean: true
          - task: CopyFiles@2
            displayName: "Copy Build Artifacts"
            inputs:
              SourceFolder: "$(Build.SourcesDirectory)"
              Contents: |
                **\bin\$(BuildConfiguration)\**
                **\bin\Output\**
                *.dacpac
              TargetFolder: "$(Build.ArtifactStagingDirectory)"
          - task: PublishBuildArtifacts@1
            displayName: "Publish Artifact: Database"
            inputs:
              PathtoPublish: "$(Build.ArtifactStagingDirectory)"
              ArtifactName: ${{variables.artifactName}}
              publishLocation: 'Container'